targets:
  $default:
    builders:
      drift_dev:
        options:
          # store datetime as ISO 8601 strings in sqlite
          store_date_time_values_as_text: true # (default)
          # path to dart file containing database description
          databases:
            foxrss: lib/database/database.dart
